### ISSUE TITLE
[FEAT] upload files to slicer

### ISSUE THREAD

**Issue by street-grease-coder** [linuxserver/docker-orcaslicer#10]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

It's an amazing project, thank you a ton. It would be great if files could be selected from the browser, and uploaded to the slicer / destination pc. It might be a bit of hassle, but it would be amazing in terms of convenience 

### Reason for change

convenience, no need to upload files to host pc anymore

### Proposed code change

redirect file selection to vnc file uploader, and select uploaded file to import

**Comment by aptalca** [comment]
At the top middle, there should be a file cabinet icon that becomes visible when you open the side menu. That icon opens a file browser and allows you to upload files into the container filesystem through the browser.
