### ISSUE TITLE
[BUG] Dockerfile TITLE spelling

### ISSUE THREAD

**Issue by kdavis** [linuxserver/docker-orcaslicer#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently is "OrcalSlicer"

### Expected Behavior

Should be "OrcaSlicer"

### Steps To Reproduce

https://github.com/kdavis/docker-orcaslicer/blob/master/Dockerfile#L11

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
-
```

### Container logs

```bash
-
```

**Comment by aptalca** [comment]
#5
