### ISSUE TITLE
Google Login - failes

### ISSUE THREAD

**Issue by ejg3855** [linuxserver/docker-orcaslicer#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click the login with google account it takes me to the page, I login, and authenticate with my mobile device then the redirect page from bambulabs just spins endlessly

### Expected Behavior

login to work properly

### Steps To Reproduce

install orca slicer
login to bambu account with network plugin

### Environment

```markdown
- OS:
- How docker service was installed: through unraid apps store
```

### CPU architecture

x86-64

### Docker creation

```bash
unsure
```

### Container logs

```bash
not sure how to provide this
```

**Comment by aptalca** [comment]
Please google `unraid docker faq` and it should tell you how to get the `docker run` and the `container logs` that we are asking for in the template

**Comment by christophtoelle** [comment]
I got the same issue, copying the link and moving it into incognito-tab did the trick for me
